BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[contratar] ALTER COLUMN [DNI] BIGINT NOT NULL;
ALTER TABLE [dbo].[contratar] ALTER COLUMN [Telefono] BIGINT NOT NULL;
ALTER TABLE [dbo].[contratar] ALTER COLUMN [Numero] BIGINT NOT NULL;
ALTER TABLE [dbo].[contratar] ALTER COLUMN [Plan] BIGINT NOT NULL;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
